apiVersion: v2
name: xenorchestra-csi-driver
description: CSI driver for Xen Orchestra
type: application
home: https://github.com/vatesfr/xenorchestra-csi-driver
icon: https://cdn.vates.tech/logos-update/logos/devops.svg
sources:
  - https://github.com/vatesfr/xenorchestra-csi-driver
keywords:
  - csi
  - storage
  - xenorchestra
  - kubernetes
version: 1.0.0-rc.1
appVersion: v1.0.0-rc.1
