apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xo-csi-pvc-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-xenorchestra-sc-dynamic # defined in csi-sc.yaml
