// Code generated by MockGen. DO NOT EDIT.
// Source: xoclient.go
//
// Generated by this command:
//
//	mockgen -source=xoclient.go -destination=mock/xoclient.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	client "github.com/vatesfr/xenorchestra-go-sdk/client"
	payloads "github.com/vatesfr/xenorchestra-go-sdk/pkg/payloads"
	library "github.com/vatesfr/xenorchestra-go-sdk/pkg/services/library"
	gomock "go.uber.org/mock/gomock"
)

// MockXoClient is a mock of XoClient interface.
type MockXoClient struct {
	ctrl     *gomock.Controller
	recorder *MockXoClientMockRecorder
	isgomock struct{}
}

// MockXoClientMockRecorder is the mock recorder for MockXoClient.
type MockXoClientMockRecorder struct {
	mock *MockXoClient
}

// NewMockXoClient creates a new mock instance.
func NewMockXoClient(ctrl *gomock.Controller) *MockXoClient {
	mock := &MockXoClient{ctrl: ctrl}
	mock.recorder = &MockXoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXoClient) EXPECT() *MockXoClientMockRecorder {
	return m.recorder
}

// AttachVDIToVM mocks base method.
func (m *MockXoClient) AttachVDIToVM(ctx context.Context, vdi payloads.VDI, vmUUID uuid.UUID) (*payloads.VBD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachVDIToVM", ctx, vdi, vmUUID)
	ret0, _ := ret[0].(*payloads.VBD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachVDIToVM indicates an expected call of AttachVDIToVM.
func (mr *MockXoClientMockRecorder) AttachVDIToVM(ctx, vdi, vmUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachVDIToVM", reflect.TypeOf((*MockXoClient)(nil).AttachVDIToVM), ctx, vdi, vmUUID)
}

// ConnectVBDToVM mocks base method.
func (m *MockXoClient) ConnectVBDToVM(ctx context.Context, vbd payloads.VBD) (*payloads.VBD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectVBDToVM", ctx, vbd)
	ret0, _ := ret[0].(*payloads.VBD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectVBDToVM indicates an expected call of ConnectVBDToVM.
func (mr *MockXoClientMockRecorder) ConnectVBDToVM(ctx, vbd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectVBDToVM", reflect.TypeOf((*MockXoClient)(nil).ConnectVBDToVM), ctx, vbd)
}

// DisconnectVBDFromVM mocks base method.
func (m *MockXoClient) DisconnectVBDFromVM(ctx context.Context, vdi payloads.VDI, vmUUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisconnectVBDFromVM", ctx, vdi, vmUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisconnectVBDFromVM indicates an expected call of DisconnectVBDFromVM.
func (mr *MockXoClientMockRecorder) DisconnectVBDFromVM(ctx, vdi, vmUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectVBDFromVM", reflect.TypeOf((*MockXoClient)(nil).DisconnectVBDFromVM), ctx, vdi, vmUUID)
}

// GetVBDFromVDIAndVM mocks base method.
func (m *MockXoClient) GetVBDFromVDIAndVM(ctx context.Context, vdi payloads.VDI, vmUUID uuid.UUID) (*payloads.VBD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVBDFromVDIAndVM", ctx, vdi, vmUUID)
	ret0, _ := ret[0].(*payloads.VBD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVBDFromVDIAndVM indicates an expected call of GetVBDFromVDIAndVM.
func (mr *MockXoClientMockRecorder) GetVBDFromVDIAndVM(ctx, vdi, vmUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVBDFromVDIAndVM", reflect.TypeOf((*MockXoClient)(nil).GetVBDFromVDIAndVM), ctx, vdi, vmUUID)
}

// Host mocks base method.
func (m *MockXoClient) Host() library.Host {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Host")
	ret0, _ := ret[0].(library.Host)
	return ret0
}

// Host indicates an expected call of Host.
func (mr *MockXoClientMockRecorder) Host() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Host", reflect.TypeOf((*MockXoClient)(nil).Host))
}

// IsVDIUsedAnywhere mocks base method.
func (m *MockXoClient) IsVDIUsedAnywhere(ctx context.Context, vdi *payloads.VDI) ([]*payloads.VBD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsVDIUsedAnywhere", ctx, vdi)
	ret0, _ := ret[0].([]*payloads.VBD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsVDIUsedAnywhere indicates an expected call of IsVDIUsedAnywhere.
func (mr *MockXoClientMockRecorder) IsVDIUsedAnywhere(ctx, vdi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsVDIUsedAnywhere", reflect.TypeOf((*MockXoClient)(nil).IsVDIUsedAnywhere), ctx, vdi)
}

// PBD mocks base method.
func (m *MockXoClient) PBD() library.PBD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PBD")
	ret0, _ := ret[0].(library.PBD)
	return ret0
}

// PBD indicates an expected call of PBD.
func (mr *MockXoClientMockRecorder) PBD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PBD", reflect.TypeOf((*MockXoClient)(nil).PBD))
}

// Pool mocks base method.
func (m *MockXoClient) Pool() library.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pool")
	ret0, _ := ret[0].(library.Pool)
	return ret0
}

// Pool indicates an expected call of Pool.
func (mr *MockXoClientMockRecorder) Pool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pool", reflect.TypeOf((*MockXoClient)(nil).Pool))
}

// SR mocks base method.
func (m *MockXoClient) SR() library.SR {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SR")
	ret0, _ := ret[0].(library.SR)
	return ret0
}

// SR indicates an expected call of SR.
func (mr *MockXoClientMockRecorder) SR() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SR", reflect.TypeOf((*MockXoClient)(nil).SR))
}

// Task mocks base method.
func (m *MockXoClient) Task() library.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Task")
	ret0, _ := ret[0].(library.Task)
	return ret0
}

// Task indicates an expected call of Task.
func (mr *MockXoClientMockRecorder) Task() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Task", reflect.TypeOf((*MockXoClient)(nil).Task))
}

// V1Client mocks base method.
func (m *MockXoClient) V1Client() client.XOClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "V1Client")
	ret0, _ := ret[0].(client.XOClient)
	return ret0
}

// V1Client indicates an expected call of V1Client.
func (mr *MockXoClientMockRecorder) V1Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "V1Client", reflect.TypeOf((*MockXoClient)(nil).V1Client))
}

// VBD mocks base method.
func (m *MockXoClient) VBD() library.VBD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VBD")
	ret0, _ := ret[0].(library.VBD)
	return ret0
}

// VBD indicates an expected call of VBD.
func (mr *MockXoClientMockRecorder) VBD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VBD", reflect.TypeOf((*MockXoClient)(nil).VBD))
}

// VDI mocks base method.
func (m *MockXoClient) VDI() library.VDI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VDI")
	ret0, _ := ret[0].(library.VDI)
	return ret0
}

// VDI indicates an expected call of VDI.
func (mr *MockXoClientMockRecorder) VDI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VDI", reflect.TypeOf((*MockXoClient)(nil).VDI))
}

// VM mocks base method.
func (m *MockXoClient) VM() library.VM {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VM")
	ret0, _ := ret[0].(library.VM)
	return ret0
}

// VM indicates an expected call of VM.
func (mr *MockXoClientMockRecorder) VM() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VM", reflect.TypeOf((*MockXoClient)(nil).VM))
}

// WaitForVDIToBeFullyAttached mocks base method.
func (m *MockXoClient) WaitForVDIToBeFullyAttached(ctx context.Context, vbdID uuid.UUID) (*payloads.VBD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForVDIToBeFullyAttached", ctx, vbdID)
	ret0, _ := ret[0].(*payloads.VBD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForVDIToBeFullyAttached indicates an expected call of WaitForVDIToBeFullyAttached.
func (mr *MockXoClientMockRecorder) WaitForVDIToBeFullyAttached(ctx, vbdID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForVDIToBeFullyAttached", reflect.TypeOf((*MockXoClient)(nil).WaitForVDIToBeFullyAttached), ctx, vbdID)
}
