{{- if include "xenorchestra-csi-driver.configSecretCreated" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xenorchestra-csi-driver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xenorchestra-csi-driver.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.config | b64enc | quote }}
{{- end }}
