{{- if and .Values.serviceAccount.create .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xenorchestra-csi-driver.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xenorchestra-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.serviceAccount.create .Values.node.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xenorchestra-csi-driver.nodeServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xenorchestra-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
