name: Build check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - 'pkg/**'
      - 'Dockerfile'
      - 'Makefile'

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up go
        timeout-minutes: 5
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Check generated mocks
        run: |
          go generate ./...
          git diff --exit-code

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=5m --config=.golangci.yml
      - name: Unit
        run: make unit
      - name: Build
        timeout-minutes: 10
        run: make build
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v4
      - name: Build image
        timeout-minutes: 10
        run: VERSION=v0.0.0-test make images
